---

- name: Install Apache
  apt: 
    name: apache2
    update_cache: yes
    state: latest


- name: Set site conf file
  template:
    src: "{{ app_name }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ app_name }}.conf"
  tags: apache

- name: Enable site
  file:
    src: "/etc/apache2/sites-available/{{ app_name }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ app_name }}.conf"
    state: link
  notify: Reload Apache
  tags: apache

- name: Remove "default" sites
  file:
    path: "/etc/apache2/sites-enabled/{{ item }}"
    state: absent
  with_items:
    - 000-default.conf
    - default-ssl.conf
  notify: Restart Apache
  tags: apache
