---
- hosts: hcc2
  roles:
    - setup
    - ufw
    - robertdebock.fail2ban
    - apache
    - mysql
    - php
    # - mosquitto
    # - cron
    # - chromium
    # - unclutter
  vars:
    ansible_become: yes
