---

# Install UFW
# https://www.raspberrypi.org/documentation/configuration/security.md
#

- name: Install UFW
  become: yes
  apt: 
    name: ufw
    update_cache: yes
    state: latest

- name: Allow needed ports
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
  loop:
    - "22"
    - "80"
    - "443"

- name: Enable UFW
  community.general.ufw:
    state: enabled