---

# Change default password for user pi
# https://www.raspberrypi.org/documentation/configuration/security.md


# Create admin user
# https://www.raspberrypi.org/documentation/configuration/security.md


# Make sudo require a password
# https://www.raspberrypi.org/documentation/configuration/security.md


### Run the Python main loop (see rc.local)


